Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RestaurantCMS.Areas.Identity.Data;

namespace RestaurantCMS.Controllers
{
    public class AuthController : Controller
    {
        private readonly SignInManager<RestaurantCMSUser> _signInManager;
        public AuthController(SignInManager<RestaurantCMSUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public IActionResult Logout()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/DishController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using RestaurantCMS.Business.Abstract;
using RestaurantCMS.Models;
using RestaurantCMS.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;

namespace RestaurantCMS.Controllers
{
    [Authorize]
    public class DishController : Controller
    {
        IDishService dishService;
        ICategoryService categoryService;
        IWebHostEnvironment webHost;

        public DishController(IDishService dishService, ICategoryService categoryService, IWebHostEnvironment webHost)
        {
            this.dishService = dishService;
            this.categoryService = categoryService;
            this.webHost = webHost;
        }
        public IActionResult Index()
        {
            List<Dish> dishes = dishService.GetAll();
            List<Category> categories = categoryService.GetAll();
            DishCategoryModel model = new DishCategoryModel
            {
                Dishes = dishes,
                Categories = categories
            };
            return View(model);
        }
        public IActionResult List()
        {
            List<Dish> dishes = dishService.GetAll();
            return View(dishes);
        }

        [HttpGet]
        public IActionResult ListByCategory(int id)
        {
            List<Dish> dishes = dishService.GetByCategoryId(id);
            List<Category> categories = categoryService.GetAll();
            DishCategoryModel model = new DishCategoryModel
            {
                Dishes = dishes,
                Categories = categories
            };
            return View(model);
        }


        [HttpGet]
        public IActionResult Add()
        {
            List<Category> categories = categoryService.GetAll();

            DishCategoryModel model = new DishCategoryModel
            {
                Categories = categories
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(DishCategoryModel model)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = webHost.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(model.Dish.ImageFile.FileName);
                string extension = Path.GetExtension(model.Dish.ImageFile.FileName);
                model.Dish.Image = fileName += DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/images/menu/" + fileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    model.Dish.ImageFile.CopyToAsync(stream);
                }

                dishService.Add(model.Dish);
                return RedirectToAction(nameof(List));
            }


            return View(model);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Dish dish = dishService.GetById(id);
            return View(dish);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Dish dish = dishService.GetById(id);
            return View(dish);
        }

        [HttpPost]
        public IActionResult Update(Dish dish)
        {


            if (ModelState.IsValid)
            {
                dishService.Update(dish);
                return RedirectToAction(nameof(List));
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            dishService.Delete(id);
            return RedirectToAction(nameof(List));
        }
    }
}

Controllers/PersonelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using RestaurantCMS.Business.Abstract;
using RestaurantCMS.Models;
using System;
using System.Collections.Generic;
using System.IO;

namespace RestaurantCMS.Controllers
{
    [Authorize]
    public class PersonelController : Controller
    {
        IPersonelService personelService;
        IWebHostEnvironment webHost;

        public PersonelController(IPersonelService personelService, IWebHostEnvironment webHost)
        {
            this.personelService = personelService;
            this.webHost = webHost;
        }

        public IActionResult Index()
        {
            List<Personel> personels = personelService.GetAll();
            return View(personels);
        }

        public IActionResult List()
        {
            List<Personel> personels = personelService.GetAll();
            return View(personels);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Personel personel)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = webHost.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(personel.ImageFile.FileName);
                string extension = Path.GetExtension(personel.ImageFile.FileName);
                personel.Image = fileName += DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/images/personels/" + fileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    personel.ImageFile.CopyToAsync(stream);
                }

                personelService.Add(personel);
                return RedirectToAction(nameof(List));
            }


            return View();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Personel personel = personelService.GetById(id);
            return View(personel);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Personel personel = personelService.GetById(id);
            return View(personel);
        }

        [HttpPost]
        public IActionResult Update(Personel personel)
        {


            if (ModelState.IsValid)
            {
                personelService.Update(personel);
                return RedirectToAction(nameof(List));
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            personelService.Delete(id);
            return RedirectToAction(nameof(List));
        }
    }
}

Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantCMS.Business.Abstract;
using RestaurantCMS.Models;
using System.Collections.Generic;

namespace RestaurantCMS.Controllers
{
    public class ReservationController : Controller
    {
        private IReservationService _reservationService;
        public ReservationController(IReservationService reservationService)
        {
            _reservationService = reservationService;
        }

        public IActionResult Index(bool check = false)
        {
            List<Reservation> reservations = _reservationService.GetAll();
           
            return View(reservations);
        }

        public IActionResult Add()
        {
            return PartialView("ReservationAdd");
        }


        [HttpPost]
        public IActionResult Add(Reservation reservation)
        {
            _reservationService.Add(reservation);
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<link href="~/css/header.css" rel="stylesheet" />

<header class="content bg-light">
    <h1 class="title fun">RestaurantCMS</h1>
    <div class="image-text">
        <div class="filter"></div>
        <img src="~/images/home-1.jpg" alt="">
        <div class="justify-left"><p class="paragraph">Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık .</p></div>
    </div>
</header>

Views/Shared/ReservationAdd.cshtml
@model RestaurantCMS.Models.Reservation

<hr />
<div style="min-height:1000px">

    <div class="row">
        <div class="col-md-12">
            <form asp-action="Add" asp-controller="Reservation">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label asp-for="FullName" class="control-label"></label>
                            <input asp-for="FullName" class="form-control" />
                            <span asp-validation-for="FullName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                            <input asp-for="PhoneNumber" class="form-control" value="0" maxlength="11" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label asp-for="Date" class="control-label">Rezervasyon Tarihi</label>
                            <input asp-for="Date" class="form-control" />
                            <span asp-validation-for="Date" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NumPerson" class="control-label">Kişi Sayısı</label>
                            <input asp-for="NumPerson" class="form-control" />
                            <span asp-validation-for="NumPerson" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group mr-auto">
                    <input type="submit" value="Rezervasyon Yap" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/_IdentityLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantCMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://css-export.github.io/styles/colors-with-tones.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantCMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/Identity/Account/Register">Kayıt Ol</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/Identity/Account/Login">Giriş Yap</a>
                        </li>       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RestaurantCMS -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantCMS</title>

    <link href="~/css/main.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/extra.css" rel="stylesheet" />
</head>
<body>
    @if (User.Identity.Name == "admin")
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-success navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantCMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Dish" asp-action="Index">Menüler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Personel" asp-action="Index">Personeller</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="~/#about">Hakkımızda</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Reservation" asp-action="Index">Rezervasyonlar</a>
                        </li>
                        <li class="nav-item ml-auto mr-5">
                            <a class="nav-link text-light bg-danger" asp-controller="Auth" asp-action="Logout">Çıkış Yap</a>

                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    }
    else
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantCMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Dish" asp-action="Index">Menüler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Personel" asp-action="Index">Personeller</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="~/#about">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="~/#reservation">Rezervasyon Yap</a>
                        </li>
                        <li class="nav-item ml-auto mr-5">
                            <a class="nav-link text-light bg-danger" asp-controller="Auth" asp-action="Logout">Çıkış Yap</a>

                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-navy text-center mt-4">
        <div class="container ">
            <h2 class="text-center">FOOTER</h2>
            <div class="container">
                &copy; 2021 - RestaurantCMS -
            </div>
            <div class="split">
                <div class="pb-4 pn">
                    <li>Lorem, ipsum dolor.</li>
                    <li>Eveniet, cumque dignissimos?</li>
                    <li>Perspiciatis, est numquam!</li>
                    <li>Voluptatibus, alias earum?</li>
                </div>
                <div class="pb-4 pn">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure aperiam inventore nemo, asperiores dolorem nisi voluptate omnis quam sit doloremque expedita architecto dicta, at consequatur.</p>
                </div>
                <div class="pb-4 pn">
                    <p>Eum quisquam deleniti facere fugit. Vero quidem sunt fuga fugit ea voluptatum placeat ullam eveniet, minima sed veritatis laboriosam. Quia cumque est cupiditate quod eum?</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>